export const CATEGORIES = [
  { name: 'Sleep', color: '#4338ca', text: '#fff' },
  { name: 'Class', color: '#2563eb', text: '#fff' },
  { name: 'Studying / Schoolwork', color: '#0d9488', text: '#fff' },
  { name: 'Eating', color: '#ea580c', text: '#fff' },
  { name: 'Social Event', color: '#db2777', text: '#fff' },
  { name: 'Exercise', color: '#16a34a', text: '#fff' },
  { name: 'Stanford Athletics / Practice', color: '#8C1515', text: '#fff' },
  { name: 'Work / Research', color: '#7c3aed', text: '#fff' },
  { name: 'Clubs / Professional Events', color: '#ca8a04', text: '#fff' },
  { name: 'Transit / Commute', color: '#6b7280', text: '#fff' },
  { name: 'Personal / Chores', color: '#92400e', text: '#fff' },
  { name: 'Leisure / Entertainment', color: '#dc2626', text: '#fff' },
  { name: 'Other', color: '#d1d5db', text: '#374151' },
];

export const CATEGORY_MAP = Object.fromEntries(
  CATEGORIES.map(c => [c.name, c])
);

export const SLOT_HEIGHT = 4; // px per 5-min slot
export const SLOT_DURATION = 5; // minutes
export const TIMELINE_START_HOUR = 6; // 6:00 AM
export const NUM_SLOTS = 288; // 6:00 AM to 6:00 AM next day (24 hours)

export const STANFORD_MAJORS = [
  'African & African American Studies',
  'American Studies',
  'Anthropology',
  'Applied Mathematics',
  'Art History',
  'Art Practice',
  'Atmosphere & Energy',
  'Biology',
  'Biomedical Computation',
  'Chemical Engineering',
  'Chemistry',
  'Chinese',
  'Civil & Environmental Engineering',
  'Classical Studies',
  'Communication',
  'Comparative Literature',
  'Computer Science',
  'Data Science',
  'Earth Systems',
  'Economics',
  'Education',
  'Electrical Engineering',
  'Energy Resources Engineering',
  'Engineering Physics',
  'English',
  'Environmental Engineering',
  'Environmental Science',
  'Film & Media Studies',
  'French',
  'Geophysics',
  'German Studies',
  'History',
  'Human Biology',
  'Industrial Engineering',
  'International Relations',
  'Italian',
  'Japanese',
  'Latin American Studies',
  'Law, Society & Justice',
  'Linguistics',
  'Management Science & Engineering',
  'Materials Science & Engineering',
  'Mathematics',
  'Mechanical Engineering',
  'Music',
  'Neuroscience',
  'Philosophy',
  'Physics',
  'Political Science',
  'Product Design',
  'Psychology',
  'Public Policy',
  'Religious Studies',
  'Science, Technology & Society',
  'Sociology',
  'Spanish & Portuguese',
  'Statistics',
  'Symbolic Systems',
  'Theater & Performance Studies',
  'Urban Studies',
  'Other',
];
